CREATE TABLE capsules (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    contents TEXT NOT NULL,
    imageurl TEXT,
    burydate DATETIME,
    opendate DATETIME
)