CREATE TABLE capsules (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    contents TEXT NOT NULL,
    imageurl TEXT,
    burydate TEXT NOT NULL,
    opendate TEXT NOT NULL,
    opennumber BIGINT NOT NULL
)